### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by eemmzz**

### CODE REVIEW

**Comment by eemmzz** [comment]
@eemmzz

**Comment by eemmzz** [comment]
lnflsf

**Comment by yngndrw** [comment]
Test should definitely be excluded. :+1:

**Comment by yngndrw** [comment]
:8ball:

**Comment by unified-place-developers** [comment]
marvellous stuff here

**Comment by unified-place-developers** [comment]
x,jkdjhlsdgnlskg

**Comment by unified-place-developers** [comment]
asfa

**Comment by unified-place-developers** [comment]
@eemmzz

**Pull request closed without merging**
